## Classe que define os elementos.
class_name Element extends Control

## Tempos de ação dos efeitos, quando eles irão ser execultados.
enum ActionTime {
	PRE_INIT, INIT, INSTANTIATED, MOVED, LINKED, UNLINKED, BAKED, DIED, ATTACK, DEFEND, END_TURN
}
enum {
	ALKALINE, ALKALINE_EARTH, LANTANIDIUM, ACTINIDIUM, TRANSITION, OTHERS, SEMI, METALLOID, HALOGEN, NOBLE, UNKNOWN
}
enum {
	SIMBOL, NAME, VALENTIA, SERIE
}

const COLOR_SERIES = {
	ALKALINE:		Color("f05459"),
	ALKALINE_EARTH: Color('FF8A3D'),
	LANTANIDIUM: 	Color('D323BC'),
	ACTINIDIUM: 	Color('00E42F'),
	TRANSITION: 	Color('4AB593'),
	OTHERS: 		Color('5994FF'),
	SEMI: 			Color('C294FF'),
	METALLOID: 		Color('00FFFF'),
	HALOGEN: 		Color('CEC469'),
	NOBLE: 			Color('84D89E'),
	UNKNOWN: 		Color('A0A0A0'),
}
const DATA = [
	{SIMBOL : "H", NAME : "HIDROGEN", VALENTIA :1, SERIE : METALLOID},
	{SIMBOL : "He", NAME : "HELIUM", VALENTIA :0, SERIE : NOBLE},
	{SIMBOL : "Li", NAME : "LITHIUM", VALENTIA :1, SERIE : ALKALINE},
	{SIMBOL : "Be", NAME : "BERYLLIUM", VALENTIA :2, SERIE : ALKALINE_EARTH},
	{SIMBOL : "B", NAME : "BORON", VALENTIA :3, SERIE : SEMI},
	{SIMBOL : "C", NAME : "CARBON", VALENTIA :4, SERIE : METALLOID},
	{SIMBOL : "N", NAME : "NITROGEN", VALENTIA :5, SERIE : METALLOID},
	{SIMBOL : "O", NAME : "OXYGEN", VALENTIA :2, SERIE : METALLOID},
	{SIMBOL : "F", NAME : "FLUORINE", VALENTIA :1, SERIE : HALOGEN},
	{SIMBOL : "Ne", NAME : "NEON", VALENTIA :0, SERIE : NOBLE},
	{SIMBOL : "Na", NAME : "SODIUM", VALENTIA :1, SERIE : ALKALINE},
	{SIMBOL : "Mg", NAME : "MAGNESIUM", VALENTIA :2, SERIE : ALKALINE_EARTH},
	{SIMBOL : "Al", NAME : "ALUMINIUM", VALENTIA :3, SERIE : OTHERS},
	{SIMBOL : "Si", NAME : "SILICON", VALENTIA :4, SERIE : SEMI},
	{SIMBOL : "P", NAME : "PHOSPHORUS", VALENTIA :5, SERIE : METALLOID},
	{SIMBOL : "S", NAME : "SULFUR", VALENTIA :6, SERIE : METALLOID},
	{SIMBOL : "Cl", NAME : "CHLORINE", VALENTIA :7, SERIE : HALOGEN},
	{SIMBOL : "Ar", NAME : "ARGON", VALENTIA :0, SERIE : NOBLE},
	{SIMBOL : "K", NAME : "POTASSIUM", VALENTIA :1, SERIE : ALKALINE},
	{SIMBOL : "Ca", NAME : "CALCIUM", VALENTIA :2, SERIE : ALKALINE_EARTH},
	{SIMBOL : "Sc", NAME : "SCANDIUM", VALENTIA :3, SERIE : TRANSITION},
	{SIMBOL : "Ti", NAME : "TITANIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "V", NAME : "VANADIUM", VALENTIA :5, SERIE : TRANSITION},
	{SIMBOL : "Cr", NAME : "CHROMIUM", VALENTIA :6, SERIE : TRANSITION},
	{SIMBOL : "Mn", NAME : "MANGANESE", VALENTIA :7, SERIE : TRANSITION},
	{SIMBOL : "Fe", NAME : "IRON", VALENTIA :6, SERIE : TRANSITION},
	{SIMBOL : "Co", NAME : "COBALT", VALENTIA :3, SERIE : TRANSITION},
	{SIMBOL : "Ni", NAME : "NICKEL", VALENTIA :3, SERIE : TRANSITION},
	{SIMBOL : "Cu", NAME : "COPPER", VALENTIA :2, SERIE : TRANSITION},
	{SIMBOL : "Zn", NAME : "ZINC", VALENTIA :2, SERIE : TRANSITION},
	{SIMBOL : "Ga", NAME : "GALLIUM", VALENTIA :3, SERIE : OTHERS},
	{SIMBOL : "Ge", NAME : "GERMANIUM", VALENTIA :4, SERIE : SEMI},
	{SIMBOL : "As", NAME : "ARSENIC", VALENTIA :5, SERIE : SEMI},
	{SIMBOL : "Se", NAME : "SELENIUM", VALENTIA :6, SERIE : SEMI},
	{SIMBOL : "Br", NAME : "BROMINE", VALENTIA :7, SERIE : HALOGEN},
	{SIMBOL : "Kr", NAME : "KRYPTON", VALENTIA :0, SERIE : NOBLE},
	{SIMBOL : "Rb", NAME : "RUBIDIUM", VALENTIA :1, SERIE : ALKALINE},
	{SIMBOL : "Sr", NAME : "STRONTIUM", VALENTIA :2, SERIE : ALKALINE_EARTH},
	{SIMBOL : "Y", NAME : "YTTRIUM", VALENTIA :3, SERIE : TRANSITION},
	{SIMBOL : "Zr", NAME : "ZIRCONIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Nb", NAME : "NIOBIUM", VALENTIA :5, SERIE : TRANSITION},
	{SIMBOL : "Mo", NAME : "MOLYBDENUM", VALENTIA :6, SERIE : TRANSITION},
	{SIMBOL : "Tc", NAME : "TECHNETIUM", VALENTIA :7, SERIE : TRANSITION},
	{SIMBOL : "Ru", NAME : "RUTHENIUM", VALENTIA :8, SERIE : TRANSITION},
	{SIMBOL : "Rh", NAME : "RHODIUM", VALENTIA :6, SERIE : TRANSITION},
	{SIMBOL : "Pd", NAME : "PALLADIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Ag", NAME : "SILVER", VALENTIA :2, SERIE : TRANSITION},
	{SIMBOL : "Cd", NAME : "CADMIUM", VALENTIA :2, SERIE : TRANSITION},
	{SIMBOL : "In", NAME : "INDIUM", VALENTIA :3, SERIE : OTHERS},
	{SIMBOL : "Sn", NAME : "TIN", VALENTIA :4, SERIE : OTHERS},
	{SIMBOL : "Sb", NAME : "ANTIMONY", VALENTIA :5, SERIE : SEMI},
	{SIMBOL : "Te", NAME : "TELLURIUM", VALENTIA :6, SERIE : SEMI},
	{SIMBOL : "I", NAME : "IODINE", VALENTIA :7, SERIE : HALOGEN},
	{SIMBOL : "Xe", NAME : "XENON", VALENTIA :0, SERIE : NOBLE},
	{SIMBOL : "Cs", NAME : "CAESIUM", VALENTIA :1, SERIE : ALKALINE},
	{SIMBOL : "Ba", NAME : "BARIUM", VALENTIA :2, SERIE : ALKALINE_EARTH},
	{SIMBOL : "La", NAME : "LANTHANUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Ce", NAME : "CERIUM", VALENTIA :4, SERIE : LANTANIDIUM},
	{SIMBOL : "Pr", NAME : "PRASEODYMIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Nd", NAME : "NEODYMIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Pm", NAME : "PROMETHIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Sm", NAME : "SAMARIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Eu", NAME : "EUROPIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Gd", NAME : "GADOLINIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Tb", NAME : "TERBIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Dy", NAME : "DYSPROSIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Ho", NAME : "HOLMIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Er", NAME : "ERBIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Tm", NAME : "THULIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Yb", NAME : "YTTERBIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Lu", NAME : "LUTETIUM", VALENTIA :3, SERIE : LANTANIDIUM},
	{SIMBOL : "Hf", NAME : "HAFNIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Ta", NAME : "TANTALUM", VALENTIA :5, SERIE : TRANSITION},
	{SIMBOL : "W", NAME : "TUNGSTEN", VALENTIA :6, SERIE : TRANSITION},
	{SIMBOL : "Re", NAME : "RHENIUM", VALENTIA :7, SERIE : TRANSITION},
	{SIMBOL : "Os", NAME : "OSMIUM", VALENTIA :8, SERIE : TRANSITION},
	{SIMBOL : "Ir", NAME : "IRIDIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Pt", NAME : "PLATINUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Au", NAME : "GOLD", VALENTIA :3, SERIE : TRANSITION},
	{SIMBOL : "Hg", NAME : "MERCURY", VALENTIA :2, SERIE : TRANSITION},
	{SIMBOL : "Tl", NAME : "THALLIUM", VALENTIA :3, SERIE : OTHERS},
	{SIMBOL : "Pb", NAME : "LEAD", VALENTIA :4, SERIE : OTHERS},
	{SIMBOL : "Bi", NAME : "BISMUTH", VALENTIA :5, SERIE : OTHERS},
	{SIMBOL : "Po", NAME : "POLONIUM", VALENTIA :4, SERIE : OTHERS},
	{SIMBOL : "At", NAME : "ASTATINE", VALENTIA :7, SERIE : HALOGEN},
	{SIMBOL : "Rn", NAME : "RADON", VALENTIA :0, SERIE : NOBLE},
	{SIMBOL : "Fr", NAME : "FRANCIUM", VALENTIA :1, SERIE : ALKALINE},
	{SIMBOL : "Ra", NAME : "RADIUM", VALENTIA :2, SERIE : ALKALINE_EARTH},
	{SIMBOL : "Ac", NAME : "ACTINIUM", VALENTIA :3, SERIE : ACTINIDIUM},
	{SIMBOL : "Th", NAME : "THORIUM", VALENTIA :4, SERIE : ACTINIDIUM},
	{SIMBOL : "Pa", NAME : "PROTACTINIUM", VALENTIA :5, SERIE : ACTINIDIUM},
	{SIMBOL : "U", NAME : "URANIUM", VALENTIA :6, SERIE : ACTINIDIUM},
	{SIMBOL : "Np", NAME : "NEPTUNIUM", VALENTIA :6, SERIE : ACTINIDIUM},
	{SIMBOL : "Pu", NAME : "PLUTONIUM", VALENTIA :6, SERIE : ACTINIDIUM},
	{SIMBOL : "Am", NAME : "AMERICIUM", VALENTIA :6, SERIE : ACTINIDIUM},
	{SIMBOL : "Cm", NAME : "CURIUM", VALENTIA :4, SERIE : ACTINIDIUM},
	{SIMBOL : "Bk", NAME : "BERKELIUM", VALENTIA :4, SERIE : ACTINIDIUM},
	{SIMBOL : "Cf", NAME : "CALIFORNIUM", VALENTIA :4, SERIE : ACTINIDIUM},
	{SIMBOL : "Es", NAME : "EINSTEINIUM", VALENTIA :3, SERIE : ACTINIDIUM},
	{SIMBOL : "Fm", NAME : "FERMIUM", VALENTIA :3, SERIE : ACTINIDIUM},
	{SIMBOL : "Md", NAME : "MENDELEVIUM", VALENTIA :3, SERIE : ACTINIDIUM},
	{SIMBOL : "No", NAME : "NOBELIUM", VALENTIA :3, SERIE : ACTINIDIUM},
	{SIMBOL : "Lr", NAME : "LAWRENCIUM", VALENTIA :2, SERIE : ACTINIDIUM},
	{SIMBOL : "Rf", NAME : "RUTHERFORDIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Db", NAME : "DUBNIUM", VALENTIA :5, SERIE : TRANSITION},
	{SIMBOL : "Sg", NAME : "SEABORGIUM", VALENTIA :6, SERIE : TRANSITION},
	{SIMBOL : "Bh", NAME : "BOHRIUM", VALENTIA :7, SERIE : TRANSITION},
	{SIMBOL : "Hs", NAME : "HASSIUM", VALENTIA :8, SERIE : TRANSITION},
	{SIMBOL : "Mt", NAME : "MEITNERIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Ds", NAME : "DARMSTADTIUM", VALENTIA :4, SERIE : TRANSITION},
	{SIMBOL : "Rg", NAME : "ROENTGENIUM", VALENTIA :3, SERIE : TRANSITION},
	{SIMBOL : "Cn", NAME : "COPERNICIUM", VALENTIA :2, SERIE : TRANSITION},
	{SIMBOL : "Nh", NAME : "NIHONIUM", VALENTIA :3, SERIE : OTHERS},
	{SIMBOL : "Fl", NAME : "FLEROVIUM", VALENTIA :4, SERIE : OTHERS},
	{SIMBOL : "Mc", NAME : "MOSCOVIUM", VALENTIA :5, SERIE : OTHERS},
	{SIMBOL : "Lv", NAME : "LIVERMORIUM", VALENTIA :6, SERIE : OTHERS},
	{SIMBOL : "Ts", NAME : "TENNESSINE", VALENTIA :6, SERIE : HALOGEN},
	{SIMBOL : "Og", NAME : "OGANESSON", VALENTIA :0, SERIE : NOBLE},
	{SIMBOL : "Uue", NAME : "UNUNENNIUM", VALENTIA :1, SERIE : ALKALINE},
]

## valor de ataque, é variável, ou seja, esse valor pode mudar de acordo com oque acontece durante o jogo.
var eletrons: int

## isotopo, geralmente o mesmo valor q o numero atomico, determina a vida.
var neutrons: int

## Indica quantos links esse elemento pode ter em simultâneo.
var valentia: int
@onready var number_electrons_in_valencia: int = valentia

## isso é basicamente oque define que tipo de elemento é, seu valor é o custo para instanciar.
@export var atomic_number: int:
	set(value):
		atomic_number = value
		eletrons = value
		neutrons = value
		valentia = DATA[atomic_number][VALENTIA]
		tooltip_text = DATA[atomic_number][NAME]

## Dicionario que define os efeitos em seus tempos de ação:[br]
## [codeblock]
## {ActionTime.INIT: Callable(self, "nome_da_func")}
## {ActionTime.INIT: nome_da_func)}
## [/codeblock]
var action_time: Dictionary
var grid_position: Vector2i

var links = {
	Vector2i.UP: null, Vector2i.DOWN: null, Vector2i.LEFT: null, Vector2i.RIGHT: null
}

var has_link: bool:
	get:
		for link in links:
			if links[link]: return true
		
		return false

var debuffs: Array[GameJudge.DebuffEffect]
var buffs: Array[GameJudge.BuffEffect]
var effect: GameJudge.SkillEffect


func reset():
	if neutrons > atomic_number:
		neutrons -= 1
	
	if neutrons < atomic_number:
		eletrons = neutrons
	
	else:
		eletrons = atomic_number
	







